CONTRY_REPLACEMENTS = {
    'abhudhabi': 'Abu Dhabi',
    'Abudhabi': 'Abu Dhabi',
    'Czechia': 'Czech Republic',
    'Чехия': 'Czech Republic',
    'Украина': 'Ukraine',
    'Румыния': 'Romania',
    'Латвия': 'Latvia',
    'Канада': 'Canada',
    'Κερατσινι': 'Greece',
    'Διακοπή ερωτήσεων': 'Greece',
    'Venezuela, Bolivarian Republic of': 'Venezuela',
    'US': 'United States',
    'USA': 'United States',
    'uk': 'United Kingdom',
    'United Kingdom,United Kingdom': 'United Kingdom',
    'Tilburg / Netherlands': 'Netherlands',
    'Tanzania, United Republic of': 'Tanzania',
    'Iran, Islamic Republic of': 'Iran',
    'Macedonia, The Former Yugoslav Republic of': 'Macedonia',
    'Moldova, Republic of': 'Moldova',
    'Milan': 'Italy',
    'NZ': 'New Zealand',
    'Oslo': 'Norway'
}
