from typing import List, Dict, Optional

COUNTRY_CODES = [
    {'country': 'American Samoa', 'code': '1684'},
    {'country': 'Anguilla', 'code': '1264'},
    {'country': 'Antigua and Barbuda', 'code': '1268'},
    {'country': 'Bahamas, Commonwealth of The', 'code': '1242'},
    {'country': 'Barbados', 'code': '1246'},
    {'country': 'Bermuda', 'code': '1441'},
    {'country': 'Cayman Islands', 'code': '1345'},
    {'country': 'Dominica', 'code': '1767'},
    {'country': 'Dominican Republic', 'code': '1829'},
    {'country': 'Grenada', 'code': '1473'},
    {'country': 'Guam', 'code': '1671'},
    {'country': 'Jamaica', 'code': '1876'},
    {'country': 'Montserrat', 'code': '1664'},
    {'country': 'Northern Mariana Islands (Former Mariana Islands District - Trust Territory of the Pacific Islands)', 'code': '1670'},
    {'country': 'Puerto Rico', 'code': '1787'},
    {'country': 'Saint Kitts and Nevis (Former Federation of Saint Christopher and Nevis)', 'code': '1869'},
    {'country': 'Saint Lucia', 'code': '1758'},
    {'country': 'Saint Vincent and the Grenadines', 'code': '1784'},
    {'country': 'Trinidad and Tobago', 'code': '1868'},
    {'country': 'Turks and Caicos Islands', 'code': '1649'},
    {'country': 'Virgin Islands, British', 'code': '1284'},
    {'country': 'Virgin Islands, United States (Former Danish West Indies)', 'code': '1340'},
    {'country': 'Dominican Republic', 'code': '1809'},
    {'country': 'Puerto Rico', 'code': '1939'},
    {'country': 'Albania', 'code': '355'},
    {'country': 'Algeria', 'code': '213'},
    {'country': 'Andorra, Principality of', 'code': '376'},
    {'country': 'Angola', 'code': '244'},
    {'country': 'Antarctica', 'code': '672'},
    {'country': 'Armenia', 'code': '374'},
    {'country': 'Aruba', 'code': '297'},
    {'country': 'Azerbaijan or Azerbaidjan (Former Azerbaijan Soviet Socialist Republic)', 'code': '994'},
    {'country': 'Bahrain, Kingdom of (Former Dilmun)', 'code': '973'},
    {'country': 'Bangladesh (Former East Pakistan)', 'code': '880'},
    {'country': 'Belarus (Former Belorussian [Byelorussian] Soviet Socialist Republic)', 'code': '375'},
    {'country': 'Belize (Former British Honduras)', 'code': '501'},
    {'country': 'Benin (Former Dahomey)', 'code': '229'},
    {'country': 'Bhutan, Kingdom of', 'code': '975'},
    {'country': 'Bolivia', 'code': '591'},
    {'country': 'Bosnia and Herzegovina', 'code': '387'},
    {'country': 'Botswana (Former Bechuanaland)', 'code': '267'},
    {'country': 'Brunei (Negara Brunei Darussalam)', 'code': '673'},
    {'country': 'Bulgaria', 'code': '359'},
    {'country': 'Burkina Faso (Former Upper Volta)', 'code': '226'},
    {'country': 'Burundi (Former Urundi)', 'code': '257'},
    {'country': 'Cambodia, Kingdom of (Former Khmer Republic, Kampuchea Republic)', 'code': '855'},
    {'country': 'Cameroon (Former French Cameroon)', 'code': '237'},
    {'country': 'Cape Verde', 'code': '238'},
    {'country': 'Central African Republic', 'code': '236'},
    {'country': 'Chad', 'code': '235'},
    {'country': 'Comoros, Union of the', 'code': '269'},
    {'country': 'Congo, Democratic Republic of the (Former Zaire)', 'code': '243'},
    {'country': 'Congo, Republic of the', 'code': '242'},
    {'country': 'Cook Islands (Former Harvey Islands)', 'code': '682'},
    {'country': 'Costa Rica', 'code': '506'},
    {'country': "Cote D'Ivoire (Former Ivory Coast)", 'code': '225'},
    {'country': 'Croatia (Hrvatska)', 'code': '385'},
    {'country': 'Cyprus', 'code': '357'},
    {'country': 'Czech Republic', 'code': '420'},
    {'country': 'Djibouti (Former French Territory of the Afars and Issas, French Somaliland)', 'code': '253'},
    {'country': 'East Timor (Former Portuguese Timor)', 'code': '670'},
    {'country': 'Ecuador', 'code': '593'},
    {'country': 'El Salvador', 'code': '503'},
    {'country': 'Equatorial Guinea (Former Spanish Guinea)', 'code': '240'},
    {'country': 'Eritrea (Former Eritrea Autonomous Region in Ethiopia)', 'code': '291'},
    {'country': 'Estonia (Former Estonian Soviet Socialist Republic)', 'code': '372'},
    {'country': 'Ethiopia (Former Abyssinia, Italian East Africa)', 'code': '251'},
    {'country': 'Falkland Islands (Islas Malvinas)', 'code': '500'},
    {'country': 'Faroe Islands', 'code': '298'},
    {'country': 'Fiji', 'code': '679'},
    {'country': 'Finland', 'code': '358'},
    {'country': 'French Guiana or French Guyana', 'code': '594'},
    {'country': 'French Polynesia (Former French Colony of Oceania)', 'code': '689'},
    {'country': 'Gabon (Gabonese Republic)', 'code': '241'},
    {'country': 'Gambia, The', 'code': '220'},
    {'country': 'Georgia (Former Georgian Soviet Socialist Republic)', 'code': '995'},
    {'country': 'Ghana (Former Gold Coast)', 'code': '233'},
    {'country': 'Gibraltar', 'code': '350'},
    {'country': 'Greenland', 'code': '299'},
    {'country': 'Guadeloupe', 'code': '590'},
    {'country': 'Guatemala', 'code': '502'},
    {'country': 'Guinea (Former French Guinea)', 'code': '224'},
    {'country': 'Guinea-Bissau (Former Portuguese Guinea)', 'code': '245'},
    {'country': 'Guyana (Former British Guiana)', 'code': '592'},
    {'country': 'Haiti', 'code': '509'},
    {'country': 'Honduras', 'code': '504'},
    {'country': 'Hong Kong', 'code': '852'},
    {'country': 'Iceland', 'code': '354'},
    {'country': 'Iraq', 'code': '964'},
    {'country': 'Ireland', 'code': '353'},
    {'country': 'Israel', 'code': '972'},
    {'country': 'Jordan (Former Transjordan)', 'code': '962'},
    {'country': 'Kenya (Former British East Africa)', 'code': '254'},
    {'country': 'Kiribati (Pronounced keer-ree-bahss) (Former Gilbert Islands)', 'code': '686'},
    {'country': "Korea, Democratic People's Republic of (North Korea)", 'code': '850'},
    {'country': 'Kuwait', 'code': '965'},
    {'country': 'Kyrgyzstan (Kyrgyz Republic) (Former Kirghiz Soviet Socialist Republic)', 'code': '996'},
    {'country': "Lao People's Democratic Republic (Laos)", 'code': '856'},
    {'country': 'Latvia (Former Latvian Soviet Socialist Republic)', 'code': '371'},
    {'country': 'Lebanon', 'code': '961'},
    {'country': 'Lesotho (Former Basutoland)', 'code': '266'},
    {'country': 'Liberia', 'code': '231'},
    {'country': 'Libya (Libyan Arab Jamahiriya)', 'code': '218'},
    {'country': 'Liechtenstein', 'code': '423'},
    {'country': 'Lithuania (Former Lithuanian Soviet Socialist Republic)', 'code': '370'},
    {'country': 'Luxembourg', 'code': '352'},
    {'country': 'Macau', 'code': '853'},
    {'country': 'Macedonia, The Former Yugoslav Republic of', 'code': '389'},
    {'country': 'Madagascar (Former Malagasy Republic)', 'code': '261'},
    {'country': 'Malawi (Former British Central African Protectorate, Nyasaland)', 'code': '265'},
    {'country': 'Maldives', 'code': '960'},
    {'country': 'Mali (Former French Sudan and Sudanese Republic)', 'code': '223'},
    {'country': 'Malta', 'code': '356'},
    {'country': 'Marshall Islands (Former Marshall Islands District - Trust Territory of the Pacific Islands)', 'code': '692'},
    {'country': 'Martinique (French)', 'code': '596'},
    {'country': 'Mauritania', 'code': '222'},
    {'country': 'Mauritius', 'code': '230'},
    {'country': 'Mayotte (Territorial Collectivity of Mayotte)', 'code': '269'},
    {'country': 'Micronesia, Federated States of (Former Ponape, Truk, and Yap Districts - Trust Territory of the Pacific Islands)', 'code': '691'},
    {'country': 'Moldova, Republic of', 'code': '373'},
    {'country': 'Monaco, Principality of', 'code': '377'},
    {'country': 'Mongolia (Former Outer Mongolia)', 'code': '976'},
    {'country': 'Morocco', 'code': '212'},
    {'country': 'Mozambique (Former Portuguese East Africa)', 'code': '258'},
    {'country': 'Namibia (Former German Southwest Africa, South-West Africa)', 'code': '264'},
    {'country': 'Nauru (Former Pleasant Island)', 'code': '674'},
    {'country': 'Nepal', 'code': '977'},
    {'country': 'Netherlands Antilles (Former Curacao and Dependencies)', 'code': '599'},
    {'country': 'New Caledonia', 'code': '687'},
    {'country': 'Nicaragua', 'code': '505'},
    {'country': 'Niger', 'code': '227'},
    {'country': 'Nigeria', 'code': '234'},
    {'country': 'Niue (Former Savage Island)', 'code': '683'},
    {'country': 'Norfolk Island', 'code': '672'},
    {'country': 'Oman, Sultanate of (Former Muscat and Oman)', 'code': '968'},
    {'country': 'Palau (Former Palau District - Trust Terriroty of the Pacific Islands)', 'code': '680'},
    {'country': 'Palestinian State (Proposed)', 'code': '970'},
    {'country': 'Panama', 'code': '507'},
    {'country': 'Papua New Guinea (Former Territory of Papua and New Guinea)', 'code': '675'},
    {'country': 'Paraguay', 'code': '595'},
    {'country': 'Portugal', 'code': '351'},
    {'country': 'Qatar, State of', 'code': '974'},
    {'country': 'Reunion (French) (Former Bourbon Island)', 'code': '262'},
    {'country': 'Rwanda (Rwandese Republic) (Former Ruanda)', 'code': '250'},
    {'country': 'Saint Helena', 'code': '290'},
    {'country': 'Saint Pierre and Miquelon', 'code': '508'},
    {'country': 'Samoa (Former Western Samoa)', 'code': '685'},
    {'country': 'San Marino', 'code': '378'},
    {'country': 'Sao Tome and Principe', 'code': '239'},
    {'country': 'Saudi Arabia', 'code': '966'},
    {'country': 'Senegal', 'code': '221'},
    {'country': 'Seychelles', 'code': '248'},
    {'country': 'Sierra Leone', 'code': '232'},
    {'country': 'Slovakia', 'code': '421'},
    {'country': 'Slovenia', 'code': '386'},
    {'country': 'Solomon Islands (Former British Solomon Islands)', 'code': '677'},
    {'country': 'Somalia (Former Somali Republic, Somali Democratic Republic)', 'code': '252'},
    {'country': 'Sudan (Former Anglo-Egyptian Sudan)', 'code': '249'},
    {'country': 'Suriname (Former Netherlands Guiana, Dutch Guiana)', 'code': '597'},
    {'country': 'Swaziland, Kingdom of', 'code': '268'},
    {'country': 'Syria (Syrian Arab Republic) (Former United Arab Republic - with Egypt)', 'code': '963'},
    {'country': 'Taiwan (Former Formosa)', 'code': '886'},
    {'country': 'Tajikistan (Former Tajik Soviet Socialist Republic)', 'code': '992'},
    {'country': 'Tanzania, United Republic of (Former United Republic of Tanganyika and Zanzibar)', 'code': '255'},
    {'country': 'Tokelau', 'code': '690'},
    {'country': 'Tonga, Kingdom of (Former Friendly Islands)', 'code': '676'},
    {'country': 'Tunisia', 'code': '216'},
    {'country': 'Turkmenistan (Former Turkmen Soviet Socialist Republic)', 'code': '993'},
    {'country': 'Tuvalu (Former Ellice Islands)', 'code': '688'},
    {'country': 'Uganda, Republic of', 'code': '256'},
    {'country': 'Ukraine (Former Ukrainian National Republic, Ukrainian State, Ukrainian Soviet Socialist Republic)', 'code': '380'},
    {'country': 'United Arab Emirates (UAE) (Former Trucial Oman, Trucial States)', 'code': '971'},
    {'country': 'Uruguay, Oriental Republic of (Former Banda Oriental, Cisplatine Province)', 'code': '598'},
    {'country': 'Uzbekistan (Former UZbek Soviet Socialist Republic)', 'code': '998'},
    {'country': 'Vanuatu (Former New Hebrides)', 'code': '678'},
    {'country': 'Vatican City State (Holy See)', 'code': '418'},
    {'country': 'Wallis and Futuna Islands', 'code': '681'},
    {'country': 'Yemen', 'code': '967'},
    {'country': 'Zambia, Republic of (Former Northern Rhodesia)', 'code': '260'},
    {'country': 'Zimbabwe, Republic of (Former Southern Rhodesia, Rhodesia)', 'code': '263'},
    {'country': 'Serbia', 'code': '381'},
    {'country': 'Montenegro', 'code': '382'},
    {'country': 'Kosovo', 'code': '383'},
    {'country': 'Afghanistan', 'code': '93'},
    {'country': 'Argentina', 'code': '54'},
    {'country': 'Australia', 'code': '61'},
    {'country': 'Austria', 'code': '43'},
    {'country': 'Belgium', 'code': '32'},
    {'country': 'Brazil', 'code': '55'},
    {'country': 'Chile', 'code': '56'},
    {'country': 'China', 'code': '86'},
    {'country': 'Christmas Island', 'code': '53'},
    {'country': 'Cocos (Keeling) Islands', 'code': '61'},
    {'country': 'Colombia', 'code': '57'},
    {'country': 'Cuba', 'code': '53'},
    {'country': 'Denmark', 'code': '45'},
    {'country': 'Egypt (Former United Arab Republic - with Syria)', 'code': '20'},
    {'country': 'France', 'code': '33'},
    {'country': 'Germany', 'code': '49'},
    {'country': 'Greece', 'code': '30'},
    {'country': 'Hungary', 'code': '36'},
    {'country': 'India', 'code': '91'},
    {'country': 'Indonesia (Former Netherlands East Indies; Dutch East Indies)', 'code': '62'},
    {'country': 'Iran, Islamic Republic of', 'code': '98'},
    {'country': 'Italy', 'code': '39'},
    {'country': 'Japan', 'code': '81'},
    {'country': 'Korea, Republic of (South Korea)', 'code': '82'},
    {'country': 'Malaysia', 'code': '60'},
    {'country': 'Mexico', 'code': '52'},
    {'country': 'Myanmar, Union of (Former Burma)', 'code': '95'},
    {'country': 'Netherlands', 'code': '31'},
    {'country': 'New Zealand (Aotearoa)', 'code': '64'},
    {'country': 'Norway', 'code': '47'},
    {'country': 'Pakistan (Former West Pakistan)', 'code': '92'},
    {'country': 'Peru', 'code': '51'},
    {'country': 'Philippines', 'code': '63'},
    {'country': 'Poland', 'code': '48'},
    {'country': 'Romania', 'code': '40'},
    {'country': 'Singapore', 'code': '65'},
    {'country': 'South Africa (Former Union of South Africa)', 'code': '27'},
    {'country': 'Spain', 'code': '34'},
    {'country': 'Sri Lanka (Former Serendib, Ceylon)', 'code': '94'},
    {'country': 'Sweden', 'code': '46'},
    {'country': 'Switzerland', 'code': '41'},
    {'country': 'Thailand (Former Siam)', 'code': '66'},
    {'country': 'Turkey', 'code': '90'},
    {'country': 'United Kingdom (Great Britain / UK)', 'code': '44'},
    {'country': 'Venezuela', 'code': '58'},
    {'country': 'Vietnam', 'code': '84'},
    {'country': 'Russian Federation', 'code': '7'},
    {'country': 'United States', 'code': '1'},
    {'country': 'Kazakstan or Kazakhstan (Former Kazakh Soviet Socialist Republic)', 'code': '7'},
    {'country': 'Canada', 'code': '1'},
]


def get_country_codes() -> List[Dict]:
    """
    Returns:
        телефонные коды стран
    """
    return COUNTRY_CODES


def get_country_by_code(country_codes: List[Dict], phone: Optional[str]) -> str:
    """ Определяет страну по телефонному коду

    Args:
        country_codes: данные о кодах стран (из Excel)
        phone: телефон для вычленения кода и определения страны

    Returns:
        название страны или пустую строку
    """
    if not phone:
        return ''
    for country_code in country_codes:
        if phone.startswith(country_code['code']):
            return country_code['country']
    return ''
