from flask import render_template, jsonify
from flask_login import login_required

from app.main import bp


class OfferConstructorDataController:
    source_book_id = '1lYWtuit6pKiOO1GV9v9sYiZ0IHLQgqxziLRkP9GKz6s'
    sheets = (
        'clinic',
        'diagnosis',
        'template',
        'advisor',
        'language',
        'therapy_type',

        'physiotherapy',
        'active_substance',
        'examination_package',
        'type_of_administration',
    )

    @classmethod
    def get_data(cls):
        return {
            "advisor": [{'id': '1', 'title': 'Aigera Yang'}, {'id': '2', 'title': 'Alexandra Newman'},
                        {'id': '3', 'title': 'Anatolio Graf'}, {'id': '4', 'title': 'Angie Miller'},
                        {'id': '5', 'title': 'Darya Zorra'}, {'id': '6', 'title': 'Ellen Bayliss'},
                        {'id': '7', 'title': 'Helen Abra'}, {'id': '8', 'title': 'Juli Manzetti'},
                        {'id': '9', 'title': 'Karen Young'}, {'id': '10', 'title': 'Manas'},
                        {'id': '11', 'title': 'Nikola Djokovic'}, {'id': '12', 'title': 'Olga Gelfer'},
                        {'id': '13', 'title': 'Ollie Skomoroshko'}, {'id': '14', 'title': 'Tanya Blanchet'},
                        {'id': '15', 'title': 'Victoria Bah'}, {'id': '16', 'title': 'Helga Vist'},
                        {'id': '17', 'title': 'Maria Smith'}, {'id': '18', 'title': 'Stella Shyk'},
                        {'id': '19', 'title': 'Tim Richard'}, {'id': '20', 'title': 'Mila Gates'},
                        {'id': '21', 'title': 'Evgeniy Yiler'}, {'id': '22', 'title': 'Millie Movich'},
                        {'id': '23', 'title': 'An Ross'}],
            "template": [{'id': '1', 'title': 'tmpl 1', 'quantity': '1', 'clinic': '2', 'days': '5',
                          'type_of_administration': '2', 'active_substance': '', 'physiotherapy': '',
                          'examination_package': '', 'therapy_type': '2'},
                         {'id': '2', 'title': 'tmpl 1', 'quantity': '1', 'clinic': '2', 'days': '5',
                          'type_of_administration': '', 'active_substance': '', 'physiotherapy': '3',
                          'examination_package': '', 'therapy_type': '3'},
                         {'id': '3', 'title': 'tmpl 2', 'quantity': '2', 'clinic': '2', 'days': '7',
                          'type_of_administration': '', 'active_substance': '', 'physiotherapy': '',
                          'examination_package': '2', 'therapy_type': '1'}],
            "clinic": [{'id': '2', 'title': 'Serbia, Belgrade clinic', 'day cost': '1400'}],
            "diagnosis": [{'id': '2', 'title': 'common',
                           'effects': "- Activation of the own stem cells pool \r\n- Activation of the body's regenerative capacity\r\n- Neoangiogenesis (stimulation of the growth of new blood vessels)\r\n- Improvement of neuromuscular conduction\r\n- Anti-inflammatory and immunomodulating effects"}],
            "type_of_administration": [{'id': '2', 'title': 'Intravenous Infusion',
                                        'description': 'General improvement of tissue regeneration, systemic anti-inflammatory effect, normalization of metabolic processes, stimulation of angiogenesis, improving of endothelial function, atherosclerosis prevention',
                                        'manager_notes': 'umbilical blood stem cells - only 1,2,3+',
                                        'therapy_type': '2, 3', 'patient_notes': '`<< для примера!',
                                        'Serbia, Belgrade clinic': 'available'},
                                       {'id': '3', 'title': 'Intrathecal Injection',
                                        'description': 'Improvement of angiogenesis of the central nervous system and nerve cells trophic (nourishment) \nIncreasement of regeneration processes\nImprovement of neuroplasticity and neurometabolism, anti-inflammatory effect',
                                        'manager_notes': 'Обычно используем Autologous Bone Marrow Mononuclear Cells (MNC). Добавить к цене 2000 евро.',
                                        'therapy_type': '2', 'patient_notes': '`<< для примера!',
                                        'Serbia, Belgrade clinic': 'available'},
                                       {'id': '4', 'title': 'Intramuscular Injection',
                                        'description': 'Enhancement of neuromuscular transmission, improvement of muscle strength in the weak extremities',
                                        'manager_notes': '1 зона: 1 рука, нога, спина = 1 базовая доза\nНо 3 зоны = 2 дозы',
                                        'therapy_type': '3', 'patient_notes': '`<< для примера!',
                                        'Serbia, Belgrade clinic': 'available'},
                                       {'id': '5', 'title': 'Retrobulbar Injection',
                                        'description': 'Improvement of microcirculation and trophicity of the retina and optic nerve. Reduction of autoimmune inflammation',
                                        'manager_notes': 'Если два глаза, то + 1000 евро. Как правило, это SVF',
                                        'therapy_type': '3', 'patient_notes': '`<< для примера!',
                                        'Serbia, Belgrade clinic': 'available'},
                                       {'id': '6', 'title': 'Intra-articular Injection',
                                        'description': 'Local anti-inflammatory effect, stopping the degeneration process in the joints, regeneration of cartilage',
                                        'manager_notes': 'Один сустав = 0,5 цены. Но минимум 1 базовая цена: shoulder joint radiocarpal joint elbow joint knee joint hip join\nВнутрь сустава - только экзосомы или SVF. Лучше назначать только экзосомы\nДругие клетки - только параартикулярно!!!\n',
                                        'therapy_type': '2', 'patient_notes': '`<< для примера!',
                                        'Serbia, Belgrade clinic': 'available'}, {'id': '7', 'title': 'Inhalation',
                                                                                  'description': 'Improvement of lung tissue regeneration, decreasement of endothelial dysfunction, local anti-inflamatory effect',
                                                                                  'manager_notes': 'Один базовый объем на весь курс',
                                                                                  'therapy_type': '2',
                                                                                  'patient_notes': '`<< для примера!',
                                                                                  'Serbia, Belgrade clinic': 'available'},
                                       {'id': '8', 'title': 'Parameatal Injection',
                                        'description': 'Local anti-inflammatory effect, improvement of auditory nerve and middle ear tissues regeneration',
                                        'manager_notes': 'Вокруг слухового канала. 1 доза. Как правило это SVF',
                                        'therapy_type': '2', 'patient_notes': '`<< для примера!',
                                        'Serbia, Belgrade clinic': 'available'}, {'id': '9', 'title': 'Para-articular',
                                                                                  'description': 'Local anti-inflammatory effect, reduce pain syndrome, improvement of joint tissues regeneration',
                                                                                  'manager_notes': 'Вокруг сустава. половина цены за один сустав.',
                                                                                  'therapy_type': '',
                                                                                  'patient_notes': '',
                                                                                  'Serbia, Belgrade clinic': 'available'},
                                       {'id': '10', 'title': 'Paravertebral injection',
                                        'description': 'Local anti-inflammatory effect, reduce pain syndrome, improvement of tissue regeneration',
                                        'manager_notes': '', 'therapy_type': '', 'patient_notes': '',
                                        'Serbia, Belgrade clinic': 'available'},
                                       {'id': '11', 'title': 'Nasal Drops (Nasal Spray)',
                                        'description': 'Improvement of neuroplasticity and neurometabolism, anti-inflammatory effect',
                                        'manager_notes': '', 'therapy_type': '', 'patient_notes': '',
                                        'Serbia, Belgrade clinic': 'available'}, {'id': '12',
                                                                                  'title': 'Para-corpus cavernosum (subcutaneously on both lateral parts)',
                                                                                  'description': 'Impact on the neurogenic component of erection, increase the capillary density and blood flow',
                                                                                  'manager_notes': 'Полная доза',
                                                                                  'therapy_type': '',
                                                                                  'patient_notes': '',
                                                                                  'Serbia, Belgrade clinic': 'available'},
                                       {'id': '13', 'title': 'Intradermal Injection (Skin Issues)',
                                        'description': 'Stimulates the owns patients stem cells, reduces wrinkles, improves the skin tone and overall pigmentations.',
                                        'manager_notes': 'Стоимость клеток на 1 зону (голова, лицо или декольте) - 2000 евро. \nОбычно назначается лицо + декольте = 4000 евро',
                                        'therapy_type': '', 'patient_notes': '',
                                        'Serbia, Belgrade clinic': 'available'},
                                       {'id': '14', 'title': 'Intradermal Injection (Hair Loss Issues)',
                                        'description': 'Improvement in the microvasculature of the scalp skin, stimulation of hair follicles. Restoration of the subcutaneous fat layer to recover hair follicle niche',
                                        'manager_notes': 'Стоимость клеток на 1 зону (только голова) - 2000 евро. ',
                                        'therapy_type': '', 'patient_notes': '',
                                        'Serbia, Belgrade clinic': 'available'},
                                       {'id': '15', 'title': 'Skin Applications',
                                        'description': 'Stimulates tissue regeneration in the area of \u200b\u200bapplication',
                                        'manager_notes': '', 'therapy_type': '', 'patient_notes': '',
                                        'Serbia, Belgrade clinic': 'available'},
                                       {'id': '16', 'title': 'Rectal Administration',
                                        'description': 'Regeneration of intestinal mucosa, improvement of microcirculatory blood flow, stimulation of angiogenesis. Local anti-inflammatory effect',
                                        'manager_notes': '', 'therapy_type': '', 'patient_notes': '',
                                        'Serbia, Belgrade clinic': 'available'},
                                       {'id': '17', 'title': 'Local Injection in the Clitoral Area',
                                        'description': 'Improvement of sensitivity, improvement of quality of life and activity, pain removing',
                                        'manager_notes': '', 'therapy_type': '', 'patient_notes': '',
                                        'Serbia, Belgrade clinic': 'available'},
                                       {'id': '18', 'title': 'Exosomes via intravenous drip infusion',
                                        'description': 'Secreted factors produce different effects: immunomodulation, tissue regenerative potential and homeostasis restoration, anti-inflammatory effect. Enhance angiogenesis, myogenesis, and hematopoiesis , induce neurogenesis and functional recovery.',
                                        'manager_notes': '', 'therapy_type': '', 'patient_notes': '',
                                        'Serbia, Belgrade clinic': 'available'},
                                       {'id': '19', 'title': 'Exosomes via intramuscular injection',
                                        'description': 'Secreted factors produce different effects: immunomodulation, tissue regenerative potential and homeostasis restoration, anti-inflammatory effect. Enhance angiogenesis, myogenesis, and hematopoiesis , induce neurogenesis and functional recovery.',
                                        'manager_notes': '', 'therapy_type': '', 'patient_notes': '',
                                        'Serbia, Belgrade clinic': 'available'},
                                       {'id': '20', 'title': 'Nasal spray to take away with you',
                                        'description': 'A set of 5 bottles is given to patients to go on with maintenance therapy for 5 more weeks',
                                        'manager_notes': 'Один базовый объем ', 'therapy_type': '', 'patient_notes': '',
                                        'Serbia, Belgrade clinic': 'available'},
                                       {'id': '21', 'title': 'Macrophages through nasal drops ',
                                        'description': 'Macrophages have anti-inflammatory and neurorestorative potential. It helps to inhibit inflammation, protect neurons from apoptosis, stimulate neurogenesis, the growth and remyelination of axons, the formation of new synapses and activate angiogenesis',
                                        'manager_notes': '', 'therapy_type': '', 'patient_notes': '',
                                        'Serbia, Belgrade clinic': 'available'}, {'id': '22', 'title': 'Eye Drops',
                                                                                  'description': 'Elimination of dry eye syndrome, correction of corneal trophic disorders',
                                                                                  'manager_notes': '',
                                                                                  'therapy_type': '',
                                                                                  'patient_notes': '',
                                                                                  'Serbia, Belgrade clinic': 'available'},
                                       {'id': '23', 'title': 'Eye Drops to take away with you',
                                        'description': 'A set of tubes is given to patients to go on with maintenance therapy for 1 month',
                                        'manager_notes': '', 'therapy_type': '', 'patient_notes': '',
                                        'Serbia, Belgrade clinic': 'available'},
                                       {'id': '24', 'title': 'Inhalation or intravenous infusion',
                                        'description': 'Improvement of lung tissue regeneration, decreasement of endothelial dysfunction, local anti-inflamatory effect',
                                        'manager_notes': '', 'therapy_type': '', 'patient_notes': '',
                                        'Serbia, Belgrade clinic': 'available'},
                                       {'id': '25', 'title': 'Skin applications to take away with you',
                                        'description': 'A set of 5 masks is given to patients to go on with maintenance therapy for 5 more weeks',
                                        'manager_notes': '', 'therapy_type': '', 'patient_notes': '',
                                        'Serbia, Belgrade clinic': 'available'},
                                       {'id': '26', 'title': 'Enemas to take away with you',
                                        'description': 'A set of 5 tubes is given to patients to go on with maintenance therapy',
                                        'manager_notes': '', 'therapy_type': '', 'patient_notes': '',
                                        'Serbia, Belgrade clinic': 'available'}],
            "active_substance": [{'id': '2', 'title': '№1 Autologous Stromal Vascular Fraction (SVF)*',
                                  'manager_notes': 'Базовый объем забора 100 мл.Объем готового преперата отличается.\nМСК, Клетки эндотелия, гладкомышечные клетки, тканевые макрофаги, лейкоциты\nВажно!!! понимать физическое состояние пациента для набора нескольких доз',
                                  'price': '4000', 'therapy_type': '2, 3', 'patient_notes': '`<< для примера!',
                                  'Serbia, Belgrade clinic': 'available'},
                                 {'id': '3', 'title': '№2 Autologous Bone Marrow Mononuclear Cells (MNC)*',
                                  'manager_notes': 'МСК, ГСК, лейкоциты. Базовый объем забора 100 мл.Объем готового преперата отличается.',
                                  'price': '4000', 'therapy_type': '2', 'patient_notes': '`<< для примера!',
                                  'Serbia, Belgrade clinic': 'available'},
                                 {'id': '4', 'title': '№3 Autologous M2 Macrophages*',
                                  'manager_notes': 'Базовый объем: 100 млн. клеток\nМСК', 'price': '4000',
                                  'therapy_type': '3', 'patient_notes': '`<< для примера!',
                                  'Serbia, Belgrade clinic': 'available'}, {'id': '5',
                                                                            'title': '№4 Allogeneic Cultivated Umbilical Cord-derived Multipotent Mesenchymal Stromal Cells',
                                                                            'manager_notes': 'Базовый объем: 100-150 млн. клеток\nМСК\n(Взрослым делают 1-2 млн на кг, поэтому доза и получается 100-150 млн)',
                                                                            'price': '5000', 'therapy_type': '3',
                                                                            'patient_notes': '`<< для примера!',
                                                                            'Serbia, Belgrade clinic': 'available'},
                                 {'id': '6', 'title': '№5 PRP (Platelet Rich Plasma)', 'manager_notes': '',
                                  'price': '500', 'therapy_type': '2', 'patient_notes': '`<< для примера!',
                                  'Serbia, Belgrade clinic': 'available'},
                                 {'id': '7', 'title': '№6 PRL (Platelet Rich Lysat)', 'manager_notes': '',
                                  'price': '500', 'therapy_type': '2', 'patient_notes': '`<< для примера!',
                                  'Serbia, Belgrade clinic': 'available'}, {'id': '8',
                                                                            'title': '№7 Allogeneic Cultivated Placenta-derived Multipotent Mesenchymal Stromal Cells',
                                                                            'manager_notes': 'Базовый объем: 100-150 млн. клеток\r\nМСК\r\n(Взрослым делают 1-2 млн на кг, поэтому доза и получается 100-150 млн)',
                                                                            'price': '5000', 'therapy_type': '2',
                                                                            'patient_notes': '`<< для примера!',
                                                                            'Serbia, Belgrade clinic': 'available'},
                                 {'id': '9',
                                  'title': '№8 Allogeneic Cultivated Gingiva-derived Multipotent Mesenchymal Stromal Cells',
                                  'manager_notes': 'Базовый объем: 100 млн. клеток МСК', 'price': '5000',
                                  'therapy_type': '', 'patient_notes': '', 'Serbia, Belgrade clinic': 'available'},
                                 {'id': '10',
                                  'title': '№9 Autologus Cultivated Gingiva-derived Multipotent Mesenchymal Stromal Cells*',
                                  'manager_notes': '', 'price': '4000', 'therapy_type': '', 'patient_notes': '',
                                  'Serbia, Belgrade clinic': 'available'}, {'id': '11',
                                                                            'title': '№10 Autologous Cultivated Fat Tissue-derived Multipotent Mesenchymal Stromal Cells*\n\n* 3-4 weeks are required for cultivation of autologous stromal cells!',
                                                                            'manager_notes': 'МСК. Собственные МСК из жировой ткани. Предварительно культивированные до терапевтической дозы (3-4 недели). Если есть потенциал',
                                                                            'price': '5000', 'therapy_type': '',
                                                                            'patient_notes': '',
                                                                            'Serbia, Belgrade clinic': 'available'},
                                 {'id': '12',
                                  'title': '№11 Autologous Cultivated Bone Marrow-derived Multipotent Mesenchymal Stromal Cells*\n\n*5-7 weeks are required for cultivation of autologous stromal cells!',
                                  'manager_notes': 'МСК. Собственные МСК из костного мозга. Предварительно культивированные до терапевтической дозы (5-7 недели). Если есть потенциал',
                                  'price': '5000', 'therapy_type': '', 'patient_notes': '',
                                  'Serbia, Belgrade clinic': 'available'},
                                 {'id': '13', 'title': '№12 Regulatory T-Cells (CD4+CD25+Foxp3+)', 'manager_notes': '',
                                  'price': '', 'therapy_type': '', 'patient_notes': '',
                                  'Serbia, Belgrade clinic': 'available'}, {'id': '14',
                                                                            'title': '№13 Autologous Cultivated Skin Fibroblasts\n\n*Own fibroblasts if there is potential.\nTaken behind the ear (0.5 cm). \nPre-cultured to a therapeutic dose (5-7 weeks).',
                                                                            'manager_notes': 'МСК. Собственные фибробласты. Предварительно культивированные до терапевтической дозы (5-7 недели). Если есть потенциал',
                                                                            'price': '5000', 'therapy_type': '',
                                                                            'patient_notes': '',
                                                                            'Serbia, Belgrade clinic': 'available'},
                                 {'id': '15', 'title': '№14 Micro Fat Grafting ', 'manager_notes': '', 'price': '3000',
                                  'therapy_type': '', 'patient_notes': '', 'Serbia, Belgrade clinic': 'available'},
                                 {'id': '16', 'title': '№16 Nano Fat Grafting ', 'manager_notes': '', 'price': '3000',
                                  'therapy_type': '', 'patient_notes': '', 'Serbia, Belgrade clinic': 'available'},
                                 {'id': '17', 'title': '№17 Secretome of Mesenchymal Stem Cells',
                                  'manager_notes': 'Базовый объем: 40 мл. НЕ ВВОДЯТСЯ В ИНЪЕКЦИЯХ! (только локально на кожу и слизистые)\nХватит:\n* На 2 маски для лица\n* 1 Клизма\n* 2 ингаляции\n* 1 Апликация на раневую поверхность или маску для одной лодони или ступни',
                                  'price': '200', 'therapy_type': '', 'patient_notes': '',
                                  'Serbia, Belgrade clinic': 'available'},
                                 {'id': '18', 'title': '№18 Secretome of Autologous M2 Macrophages',
                                  'manager_notes': 'Macrophages have anti-inflammatory and neurorestorative potential. It helps to inhibit inflammation, protect neurons from apoptosis, stimulate neurogenesis, the growth and remyelination of axons, the formation of new synapses and activate angiogenesis',
                                  'price': '450', 'therapy_type': '', 'patient_notes': '',
                                  'Serbia, Belgrade clinic': 'available'},
                                 {'id': '19', 'title': '№19 Exosomes of Mesenchymal Stem Cells',
                                  'manager_notes': 'Все виды инъекций: \niv. im, pa, etc.\n+ Nasal Drops',
                                  'price': '200', 'therapy_type': '', 'patient_notes': '',
                                  'Serbia, Belgrade clinic': 'available'},
                                 {'id': '20', 'title': '№20 Exosomes of Mesenchymal Stem Cells in bottles ',
                                  'manager_notes': '2000 за 5 бутылок', 'price': '2000', 'therapy_type': '',
                                  'patient_notes': '', 'Serbia, Belgrade clinic': 'available'},
                                 {'id': '21', 'title': '№21 Exosomes of Mesenchymal Stem Cells in tubes ',
                                  'manager_notes': '2000 за 30 пробирок', 'price': '2000', 'therapy_type': '',
                                  'patient_notes': '', 'Serbia, Belgrade clinic': 'available'},
                                 {'id': '22', 'title': '№22 Secretome of Mesenchymal Stem Cells in applications ',
                                  'manager_notes': '1000 за 5 масок', 'price': '1000', 'therapy_type': '',
                                  'patient_notes': '', 'Serbia, Belgrade clinic': 'available'},
                                 {'id': '23', 'title': '№23 Secretome of Mesenchymal Stem Cells in tubes ',
                                  'manager_notes': '1000 за 5 бутылок', 'price': '1000', 'therapy_type': '',
                                  'patient_notes': '', 'Serbia, Belgrade clinic': 'available'}],
            "physiotherapy": [{'id': '2', 'title': 'IMR Therapy (Intracellular Metabolism Recovery Therapy)*',
                               'description': 'Increases and prolongs the effect of stem cell therapy up to 2-3 times. \nRestores the general metabolism, compensates for the deficiency of metabolic substrates and coenzymes. ',
                               'price': '0', 'therapy_type': '2, 3', 'patient_notes': '`<< для примера!',
                               'Serbia, Belgrade clinic': 'available',
                               'type': 'A set of antioxidants, amino acids, vitamins and microelements',
                               'manager notes': 'Mаксимальное количество процедур = количество дней - 1. По возможности лучше ставить - 2 (например 7 дней = 5 IMR)'},
                              {'id': '3', 'title': 'Plasmapheresis*',
                               'description': 'Removes autoantibodies and other harmful substances from blood circulation',
                               'price': '500', 'therapy_type': '2', 'patient_notes': '`<< для примера!',
                               'Serbia, Belgrade clinic': 'available', 'type': 'Extracorporeal Therapy'},
                              {'id': '4', 'title': 'Dialysis',
                               'description': 'Removes extra fluid and waste products from your blood when the kidneys are not able to',
                               'price': '250', 'therapy_type': '3', 'patient_notes': '`<< для примера!',
                               'Serbia, Belgrade clinic': 'available', 'type': 'Extracorporeal Therapy',
                               'manager notes': 'Проводится 3 раза в неделю для большинства пациентов с почечной недостаточностью'},
                              {'id': '5', 'title': 'Kinesiotherapy',
                               'description': 'Restores the mobility and muscle function, induces alternative neural pathways',
                               'price': '50', 'therapy_type': '3', 'patient_notes': '`<< для примера!',
                               'Serbia, Belgrade clinic': 'available', 'type': 'Personal Training',
                               'manager notes': 'Не включать в программы для АЛС'},
                              {'id': '6', 'title': 'Medical Massage',
                               'description': 'Relaxes muscles, decreases spasticity and helps body to achieve its full range of movement potential. Relieves pain, increases blood circulation, has a general positive effect.',
                               'price': '50', 'therapy_type': '2', 'patient_notes': '`<< для примера!',
                               'Serbia, Belgrade clinic': 'available', 'type': 'Manual therapy'},
                              {'id': '7', 'title': 'Speech Therapy', 'description': 'Speech function improvement',
                               'price': '50', 'therapy_type': '2', 'patient_notes': '`<< для примера!',
                               'Serbia, Belgrade clinic': 'available', 'type': 'Individual Sessions'},
                              {'id': '8', 'title': 'Occupational Therapy',
                               'description': 'Occupational therapist helps people to overcome challenges completing everyday tasks or activities',
                               'price': '50', 'therapy_type': '2', 'patient_notes': '`<< для примера!',
                               'Serbia, Belgrade clinic': 'available', 'type': 'Individual Sessions'},
                              {'id': '9', 'title': 'Lymphatic Drainage Therapy ',
                               'description': 'Improves the circulation of the lymph through the body. It helps remove waste and toxins from the body tissues',
                               'price': '60', 'therapy_type': '', 'patient_notes': '',
                               'Serbia, Belgrade clinic': 'available', 'type': 'Physiotherapy',
                               'manager notes': 'нельзя назначать при высоком Д-димере, тромбофилии, массивных ранах и повреждениях кожи ног'},
                              {'id': '10', 'title': 'Hyperbaric Oxygenation',
                               'description': 'Accelerates the blood oxygenation. \nStimulates metabolism, increases the amount of oxygen available to the cells, creates a less acidic environment within the body. Relieves muscle spasms and pain',
                               'price': '60', 'therapy_type': '', 'patient_notes': '',
                               'Serbia, Belgrade clinic': 'available', 'type': 'Physiotherapy',
                               'manager notes': 'Нельзя назначать:\n-Детям\n- Пациентам с тяжелыми ограничениями мобильности (передвигаются в кресле, не могут самостоятельно сесть, подтянуться, двигаться в положении лёжа)'},
                              {'id': '11', 'title': 'Super Inductive System (SIS)',
                               'description': 'High-intensity electromagnetic field, which positively influences the human tissue. Relieves pain, increases the mobility of the joints, accelerates the fracture healing, relaxes or strengthens muscles',
                               'price': '60', 'therapy_type': '', 'patient_notes': '',
                               'Serbia, Belgrade clinic': 'available', 'type': 'Physiotherapy',
                               'manager notes': 'противопоказан при наличии металлических протезов в месте применения, кардиостимулятора'},
                              {'id': '12', 'title': 'Spark/Shock Wave Therapy',
                               'description': 'Spark Wave is a therapy that activates processes of the recovery in almost all tissues of the body and stimulates the regenerative processes in them',
                               'price': '200', 'therapy_type': '', 'patient_notes': '',
                               'Serbia, Belgrade clinic': 'available', 'type': 'Physiotherapy',
                               'manager notes': 'не проникает через костную ткань, \nне используется на голове и легких'},
                              {'id': '13', 'title': 'MBST',
                               'description': 'Targeted impact on the treated tissue allows launching regenerative processes and self-healing mechanisms',
                               'price': '200', 'therapy_type': '', 'patient_notes': '',
                               'Serbia, Belgrade clinic': 'available', 'type': 'Physiotherapy',
                               'manager notes': 'противопоказан при наличии металлических протезов в месте применения, кардиостимулятора'},
                              {'id': '14', 'title': 'Emsella HIFEM',
                               'description': 'Harnesses the power of focused electromagnetic technology, called HIFEM, to stimulate the entire pelvic floor muscle.',
                               'price': '120', 'therapy_type': '', 'patient_notes': '',
                               'Serbia, Belgrade clinic': 'available', 'type': 'Physiotherapy',
                               'manager notes': 'противопоказан при наличии металлических протезов в месте применения, кардиостимулятора'},
                              {'id': '15',
                               'title': 'Combined physiotherapy\n\nMay include:\n- Electrotherapy\n- Ultrasound Therapy\n- Low Level Laser Light',
                               'description': '-    Reduction of chronic and acute pain;\n-    Shortening the rehabilitation period;\n-    Increasing muscle tone and functional endurance;\n-    Increasing peripheral blood circulation;\n-    Anti-inflammatory effect;\n-    Stabilization of the autonomic nervous and the central nervous systems activity\n-    Stimulation of cell functioning, including MSC cells',
                               'price': '60', 'therapy_type': '', 'patient_notes': '',
                               'Serbia, Belgrade clinic': 'available', 'type': 'Physiotherapy',
                               'manager notes': 'можно назначать при наличии противопоказаний к электротерапии (тога будут применяться ультразвук и лазер)'},
                              {'id': '16', 'title': 'Electromyostimulation',
                               'description': 'Increase or preserve muscle function and mass, increase functional endurance',
                               'price': '60', 'therapy_type': '', 'patient_notes': '',
                               'Serbia, Belgrade clinic': 'available', 'type': 'Physiotherapy',
                               'manager notes': 'разновидность электротерапии\nпротивопоказан при наличии металлических протезов в месте применения, кардиостимулятора'},
                              {'id': '17', 'title': 'Horizontal Electrostimulation',
                               'description': 'Improves nerve conduction reduces paresthesia, spasms and other manifestations of neuropathy',
                               'price': '60', 'therapy_type': '', 'patient_notes': '',
                               'Serbia, Belgrade clinic': 'available', 'type': 'Physiotherapy',
                               'manager notes': '\nпротивопоказан при наличии металлических протезов в месте применения, кардиостимулятора'},
                              {'id': '18', 'title': 'Ultrasound Therapy',
                               'description': 'Heating of tissues and micro-massage leads to healing, restoring, analgesic, anti-inflammatory, and bactericidal action',
                               'price': '50', 'therapy_type': '', 'patient_notes': '',
                               'Serbia, Belgrade clinic': 'available', 'type': 'Physiotherapy',
                               'manager notes': 'назначается в комбинации с электротерапией и LLL.'},
                              {'id': '19', 'title': 'Low Level Laser Light',
                               'description': 'Stimulates and enhances cell function, including MSC cells\nRelieves pain',
                               'price': '50', 'therapy_type': '', 'patient_notes': '',
                               'Serbia, Belgrade clinic': 'available', 'type': 'Physiotherapy',
                               'manager notes': 'обычно назначается в комбинации с электротерапией и ультразвуком.'},
                              {'id': '20', 'title': 'HILT (High Energy Laser Therapy)',
                               'description': 'Penetrates into the deep layers of tissues, carrying out their biostimulation. Possesses analgesic and anti-inflammatory action',
                               'price': '60', 'therapy_type': '', 'patient_notes': '',
                               'Serbia, Belgrade clinic': 'available', 'type': 'Physiotherapy',
                               'manager notes': 'нельзя назначать на суставы, если были локальные инъекции (интраартикулярные) в программе (гиалуронка, коллаген и клетки), так как может разрушить введенное вещество'},
                              {'id': '21', 'title': 'ILBI (Intravenous Laser Blood Irradiation)',
                               'description': 'Improves the ability of red blood cells to carry oxygen,stimulates the oxygenation, improve microcirculation and affect vascular endothelium. Also it helps to reduce high cholesterol and triglyceride levels',
                               'price': '60', 'therapy_type': '', 'patient_notes': '',
                               'Serbia, Belgrade clinic': 'available', 'type': 'Physiotherapy',
                               'manager notes': 'повышает Д-димер!'}, {'id': '22', 'title': 'Radiofrequency ',
                                                                       'description': 'Heats up deepest layers of skin and stimulate collagen and elastin production for tightening the skin.',
                                                                       'price': '0', 'therapy_type': '',
                                                                       'patient_notes': '',
                                                                       'Serbia, Belgrade clinic': 'available',
                                                                       'type': 'Aesthetic cosmetology',
                                                                       'manager notes': 'Назначается комплексом Radiofrequency +Microneedles+MSC. Всё вместе стоит 4000'},
                              {'id': '23', 'title': 'Microneedles',
                               'description': 'Stimulate local regeneration in the outer layer, diminishing fine lines, wrinkles and hyperpigmentations.',
                               'price': '0', 'therapy_type': '', 'patient_notes': '',
                               'Serbia, Belgrade clinic': 'available', 'type': 'Aesthetic cosmetology',
                               'manager notes': 'Назначается комплексом Radiofrequency +Microneedles+MSC. Всё вместе стоит 4000'}],
            "examination_package": [{'id': '2', 'title': 'General Check-up',
                                     'description': '- ECG\n- Pulse Oximetry\n- Daily monitoring of vital signs (blood pressure, pulse, temperature, respiration)\n',
                                     'price': '0', 'therapy_type': '2, 3', 'patient_notes': '`<< для примера!',
                                     'Serbia, Belgrade clinic': 'available'},
                                    {'id': '3', 'title': 'Extended Laboratory Examination',
                                     'description': '-Complete blood count\n-Metabolic status\n-Coagulation profile\n-Hormonal studies\n-General urine analysis\n-Screening for infections',
                                     'price': '0', 'therapy_type': '2', 'patient_notes': '`<< для примера!',
                                     'Serbia, Belgrade clinic': 'available'}, {'id': '4',
                                                                               'title': 'Consultations and daily examination of specialists in the clinic',
                                                                               'description': 'The attending physician determines the indications for specialist consultations based on the results of the examination.',
                                                                               'price': '0', 'therapy_type': '3',
                                                                               'patient_notes': '`<< для примера!',
                                                                               'Serbia, Belgrade clinic': 'available'},
                                    {'id': '5', 'title': 'Examination of the Regenerative Potential of Own Stem\nCells',
                                     'description': '1 year Stem Cell storage is included', 'price': '1000',
                                     'therapy_type': '3', 'patient_notes': '`<< для примера!',
                                     'Serbia, Belgrade clinic': 'available'},
                                    {'id': '6', 'title': 'A comprehensive individual diagnostic program',
                                     'description': 'Includes an expanded laboratory complex, hardware studies and consultations with specialists in accordance with the indications and individual condition of the patient',
                                     'price': '3000', 'therapy_type': '2', 'patient_notes': '`<< для примера!',
                                     'Serbia, Belgrade clinic': 'available'}, {'id': '7', 'title': 'Food Intolerance ',
                                                                               'description': "Measures your body's immune response to different foods",
                                                                               'price': '50', 'therapy_type': '2',
                                                                               'patient_notes': '`<< для примера!',
                                                                               'Serbia, Belgrade clinic': 'available'},
                                    {'id': '8', 'title': 'Heavy Metal Test',
                                     'description': 'A heavy metal blood test is a group of tests that measures the levels of possibly harmful metals in your blood',
                                     'price': '100', 'therapy_type': '2', 'patient_notes': '`<< для примера!',
                                     'Serbia, Belgrade clinic': 'available'}, {'id': '9', 'title': 'Tumor Markers*',
                                                                               'description': 'Measured before and during regenerative treatment if cancer is suspected or if there is a history of cancer treatment',
                                                                               'price': '50', 'therapy_type': '',
                                                                               'patient_notes': '',
                                                                               'Serbia, Belgrade clinic': 'available'},
                                    {'id': '10', 'title': 'Orthopedic Examination',
                                     'description': 'Carried out by a regenerative specialist in the clinic',
                                     'price': '0', 'therapy_type': '', 'patient_notes': '',
                                     'Serbia, Belgrade clinic': 'available'},
                                    {'id': '11', 'title': 'Ophthalmological Examination*',
                                     'description': 'Instrumental examinations according to indications and consultation with an ophthalmologist',
                                     'price': '200', 'therapy_type': '', 'patient_notes': '',
                                     'Serbia, Belgrade clinic': 'available'},
                                    {'id': '12', 'title': 'An electroencephalogram (EEG)*',
                                     'description': 'A test that measures electrical activity in the brain',
                                     'price': '200', 'therapy_type': '', 'patient_notes': '',
                                     'Serbia, Belgrade clinic': 'available'},
                                    {'id': '13', 'title': 'Ultrsound diagnostic*',
                                     'description': 'Examination of internal organs according to indications',
                                     'price': '100', 'therapy_type': '', 'patient_notes': '',
                                     'Serbia, Belgrade clinic': 'available'}, {'id': '14', 'title': 'X-Ray ',
                                                                               'description': 'Examination of internal organs according to indications',
                                                                               'price': '100', 'therapy_type': '',
                                                                               'patient_notes': '',
                                                                               'Serbia, Belgrade clinic': 'available'},
                                    {'id': '15', 'title': 'MRI / CT Scan*',
                                     'description': 'The examination option is determined based on the indications and contraindications of a particular patient',
                                     'price': '300', 'therapy_type': '', 'patient_notes': '',
                                     'Serbia, Belgrade clinic': 'available'},
                                    {'id': '16', 'title': 'Cognitive Function Test',
                                     'description': 'Allows us to evaluate cognitive functions and compare them with the results before treatment',
                                     'price': '0', 'therapy_type': '', 'patient_notes': '',
                                     'Serbia, Belgrade clinic': 'available'},
                                    {'id': '17', 'title': 'Autism Spectrum Screening',
                                     'description': 'Used to evaluate treatment outcomes in patients with Autism Spectrum Disorder',
                                     'price': '0', 'therapy_type': '', 'patient_notes': '',
                                     'Serbia, Belgrade clinic': 'available'}],
            "therapy_type": [{'id': '2', 'title': 'Preliminary Examination'}, {'id': '3', 'title': 'Stem Cell Therapy'},
                             {'id': '4', 'title': 'Regenerative Therapy'}, {'id': '5', 'title': 'IMR'}],
            "language": [{'id': '1', 'title': 'EN'}, {'id': '2', 'title': 'IT'}, {'id': '3', 'title': 'GE'},
                         {'id': '4', 'title': 'FR'}],
        }
        sheets = GoogleAPIClient(book_id=cls.source_book_id).sheets
        return {
            title: GoogleAPIClient(book_id=cls.source_book_id, sheet_title=title).get_sheet()
            for title in sheets.values()
            if title in cls.sheets
        }


@bp.route('/offer')
@login_required
def offer():
    return render_template('offer.html')


@bp.route('/load_offer_data', methods=['GET', 'POST'])
def load_offer_data():
    data = OfferConstructorDataController.get_data()
    for k, v in data.items():
        print(f'"{k}": {v},')
    return jsonify(data)


@bp.route('/save_offer', methods=['GET', 'POST'])
def save_offer():
    return jsonify({'message': 'offer saved'})


@bp.route('/build_offer', methods=['GET', 'POST'])
def build_offer():
    return jsonify({'message': 'offer builded'})
